### ISSUE TITLE
Move stylus dependency to the peerDependencies field

### ISSUE THREAD

**Issue by ym-project** [ym-project/esbuild-stylus-loader#7]
## Why?
Some projects prefer certain package version or just can't update because it will break a code. So `stylus` dependency should be moved to the peerDependencies field with supported version range.

## Tasks:
- [x] find out a minimal supported version of stylus
- [x] move stylus from dependencies field to the peerDependencies field
- [x] add information to the README file
